#include "subtitle_kit.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "iso.h"

#ifdef _WIN32
#include <direct.h>
#define mkdir_one(p) _mkdir(p)
#else
#define mkdir_one(p) mkdir(p, 0755)
#endif

#define RAW_SECTOR 2352
#define MAX_CHANNELS 32

typedef struct {
    FILE *img;
    FILE *index;
    const char *subdir;   /* pack_dir/subtitles */
    int tracks;
    char **seen;          /* track names already written (some movies are on both discs) */
    int seen_count;
} Kit;

static int already_seen(Kit *k, const char *track) {
    for (int i = 0; i < k->seen_count; i++) {
        if (strcmp(k->seen[i], track) == 0) {
            return 1;
        }
    }
    k->seen = realloc(k->seen, (k->seen_count + 1) * sizeof *k->seen);
    k->seen[k->seen_count] = malloc(strlen(track) + 1);
    strcpy(k->seen[k->seen_count++], track);
    return 0;
}

static void write_template(Kit *k, const char *track, double seconds, const char *what) {
    char path[1024];
    if (already_seen(k, track)) {
        return;
    }
    snprintf(path, sizeof path, "%s/%s.srt", k->subdir, track);
    fprintf(k->index, "%s.srt\n", track);
    k->tracks++;
    FILE *existing = fopen(path, "r");
    if (existing) {
        fclose(existing); /* never overwrite a translator's work */
        return;
    }
    FILE *f = fopen(path, "w");
    if (!f) {
        return;
    }
    long ms = (long)(seconds * 1000.0 + 0.5);
    /* One placeholder cue spanning the track: replace it with the real lines. */
    fprintf(f, "1\n00:00:00,000 --> %02ld:%02ld:%02ld,%03ld\n(%s, %.1f s: replace with timed lines)\n",
            ms / 3600000, ms / 60000 % 60, ms / 1000 % 60, ms % 1000, what, seconds);
    fclose(f);
}

/* XA voice files: channels are interleaved sector by sector. Each audio sector
 * (submode bit 2) carries 18 sound groups; its duration follows from the coding
 * byte (bit 0 stereo, bit 2 18.9 kHz, bit 4 8-bit samples). */
static void on_xa_file(const char *name, uint32_t lba, uint32_t size, void *user) {
    Kit *k = user;
    double seconds[MAX_CHANNELS] = {0};
    uint8_t hdr[24];
    for (uint32_t s = 0; s < (size + 2047) / 2048; s++) {
        if (fseek(k->img, (long)(lba + s) * RAW_SECTOR, SEEK_SET) != 0 || fread(hdr, 1, 24, k->img) != 24) {
            break;
        }
        uint8_t chan = hdr[17], submode = hdr[18], coding = hdr[19];
        if (!(submode & 0x04) || chan >= MAX_CHANNELS) {
            continue;
        }
        int stereo = coding & 1, rate = (coding & 4) ? 18900 : 37800, bits8 = coding & 0x10;
        int samples = (bits8 ? 18 * 4 * 28 : 18 * 8 * 28) / (stereo ? 2 : 1);
        seconds[chan] += (double)samples / rate;
    }
    for (int c = 0; c < MAX_CHANNELS; c++) {
        if (seconds[c] > 0.05) {
            char track[96], what[96];
            snprintf(track, sizeof track, "%s.ch%02d", name, c);
            snprintf(what, sizeof what, "voice %s channel %d", name, c);
            write_template(k, track, seconds[c], what);
        }
    }
}

/* STR movies stream at double speed (150 sectors/s). */
static void on_movie_file(const char *name, uint32_t lba, uint32_t size, void *user) {
    (void)lba;
    Kit *k = user;
    size_t n = strlen(name);
    if (n < 4 || strcmp(name + n - 4, ".STR") != 0) {
        return;
    }
    write_template(k, name, (double)((size + 2047u) / 2048u) / 150.0, "movie");
}

int subkit_write_templates(const char *const *disc_bins, int disc_count, const char *pack_dir,
                           const char *language_name) {
    char path[1024];
    /* Create the parent (<data>/lang) and the pack folder. */
    snprintf(path, sizeof path, "%s", pack_dir);
    char *slash = strrchr(path, '/');
#ifdef _WIN32
    char *bslash = strrchr(path, '\\');
    if (!slash || (bslash && bslash > slash)) {
        slash = bslash;
    }
#endif
    if (slash) {
        *slash = 0;
        mkdir_one(path);
    }
    mkdir_one(pack_dir);
    snprintf(path, sizeof path, "%s/subtitles", pack_dir);
    mkdir_one(path);

    Kit k = {0};
    char subdir[1024];
    snprintf(subdir, sizeof subdir, "%s", path);
    k.subdir = subdir;
    snprintf(path, sizeof path, "%s/subtitles/index.txt", pack_dir);
    k.index = fopen(path, "w");
    if (!k.index) {
        return -1;
    }
    fprintf(k.index, "# One subtitle file per line (generated by the template kit).\n");
    for (int d = 0; d < disc_count; d++) {
        k.img = fopen(disc_bins[d], "rb");
        if (!k.img) {
            continue;
        }
        iso_list_dir(k.img, "XA", on_xa_file, &k);
        iso_list_dir(k.img, "MOVIE", on_movie_file, &k);
        iso_list_dir(k.img, "MOVIE2", on_movie_file, &k);
        fclose(k.img);
    }
    fclose(k.index);
    for (int i = 0; i < k.seen_count; i++) {
        free(k.seen[i]);
    }
    free(k.seen);

    snprintf(path, sizeof path, "%s/pack.txt", pack_dir);
    FILE *meta = fopen(path, "r");
    if (meta) {
        fclose(meta);
    } else if ((meta = fopen(path, "w"))) {
        fprintf(meta, "name = %s\nauthor = \nversion = 1\n", language_name);
        fclose(meta);
    }
    return k.tracks;
}
