/* Generated by port/tools/gen_protos.py from the game .c definitions. Do not edit. */
#ifndef GAME_PROTOS_H
#define GAME_PROTOS_H

void anim_apply_mask(u32 *dst, s32 x, s32 stride, s32 rows); /* 80013138.c */
void anim_decoder_init(s32 arg0, s32 arg1); /* 80013138.c */
void anim_decompress_mask(void); /* 80013138.c */
s32 anim_next_frame(void); /* 80013138.c */
s32 anim_open_archive(u8 *archive); /* 80013138.c */
void audio_node_play(void); /* 800379C8.c */
u8 audio_node_update(void); /* 800379C8.c */
void bg_curve_draw(s32 index); /* 800379C8.c */
void bg_curve_randomize(s32 index, s32 mirror); /* 800379C8.c */
void bg_curve_step(s32 index); /* 800379C8.c */
void bg_curves_free(void); /* 800379C8.c */
void bg_curves_init(void); /* 800379C8.c */
void bg_curves_update(void); /* 800379C8.c */
void bgm_fade_in(void); /* 80023468.c */
void bgm_fade_out(void); /* 80023468.c */
void bgm_play(void); /* 80023468.c */
void bgm_select_slot(s16 slot); /* 80023468.c */
void bgm_stop(void); /* 80023468.c */
void bgm_stop_main(void); /* 80023468.c */
void camera_init(void); /* 800281A8.c */
void camera_set_view(s32 view); /* 800281A8.c */
s32 cd_detect_disc(void); /* 80039734.c */
s32 cd_find_file(char *name, s32 *size); /* 80013138.c */
s32 cd_lid_watch(void); /* 80039734.c */
void cd_lid_watch_reset(void); /* 80039734.c */
s32 cd_load_file_by_id(s32 fileId, u8 *dest); /* 80013138.c */
s32 cd_load_file_by_name(char *name, u8 *dest); /* 80013138.c */
void cd_loader_init(void); /* 80013138.c */
s32 cd_poll_drive_status(void); /* 80039734.c */
s32 cd_poll_load(s32 index); /* 80013138.c */
void cd_ready_callback(u8 status, u8 *result); /* 80013138.c */
void cd_seek_current_slot(void); /* 80013138.c */
void cd_sync_callback(u8 status, u8 *result); /* 80013138.c */
void credits_run(void); /* 80039734.c */
void credits_upload_scroll(s32 pos, u32 *blank, u32 *tim0, u32 *tim1, u32 *tim2); /* 80039734.c */
void debug_log_open(char *logName); /* 800379C8.c */
void debug_printf(const char *fmt, ...); /* 800379C8.c */
void disc_change_draw_screen(s32 mode, s32 cursor, s32 state); /* 8003CB08.c */
void disc_change_request(s32 arg0); /* 8003CB08.c */
void ending_movie_play(void); /* 80018F48.c */
void fog_disable(void); /* 800281A8.c */
void fog_enable(u8 r, u8 g, u8 b, s16 dqa); /* 800281A8.c */
s32 font_copy_glyph(s32 pos, s32 ch, s32 wide); /* 8001D114.c */
s32 font_render_string(char *text, s32 x, s32 y, s32 mode, s32 wide); /* 8001D114.c */
s32 func_800220C4(void); /* 8001D114.c */
void func_800220CC(void); /* 800220CC.c */
void func_800220D4(void); /* 800220CC.c */
void func_800220DC(void); /* 800220CC.c */
void func_800395E8(void); /* 800379C8.c */
void func_800395F0(void); /* 800379C8.c */
void game_boot_init(void); /* 80013138.c */
void game_restart_reset(void); /* 80013138.c */
void game_vsync_callback(void); /* 80013138.c */
void gate_models_init(void); /* 80031378.c */
void gate_models_update(void); /* 80031378.c */
void gate_scene_run(void); /* 80039734.c */
void gate_scroll_texture(void); /* 80031378.c */
s32 gfx_bg_load_step(s32 skipLast); /* 8003D6A8.c */
void gfx_frame_begin(void); /* 800281A8.c */
void gfx_frame_end(void); /* 800281A8.c */
void gfx_init(void); /* 80023468.c */
void gfx_reinit_debug_font(void); /* 80013138.c */
void *heap_alloc(u32 size); /* 80039734.c */
s32 heap_check_block(void *ptr); /* 80039734.c */
void heap_free(void *ptr); /* 80039734.c */
s32 heap_get_free(void); /* 80039734.c */
s32 heap_get_peak(void); /* 80039734.c */
void idle_play_random_media(void); /* 80018F48.c */
void idle_play_random_movie(void); /* 80018F48.c */
void idle_play_random_voice(void); /* 80018F48.c */
void jump_menu_draw(void); /* 80013138.c */
void jump_menu_init(void); /* 80013138.c */
void jump_menu_set_level(s32 number); /* 80013138.c */
void jump_menu_slide_in(void); /* 80013138.c */
void jump_menu_slide_out(void); /* 80013138.c */
void lain_anim_free_idle(void); /* 800220CC.c */
void lain_anim_idle_update(s32 arg0); /* 800220CC.c */
void lain_anim_init(void); /* 8001D114.c */
s32 lain_anim_is_idle(void); /* 800220CC.c */
s32 lain_anim_load_level_move(s32 bank); /* 8001D114.c */
s32 lain_anim_load_move(s32 set); /* 8001D114.c */
void lain_anim_load_random_idle(s32 index); /* 8001D114.c */
s32 lain_anim_load_save(void); /* 8001D114.c */
s32 lain_anim_load_select(s32 set); /* 8001D114.c */
s32 lain_anim_load_set6(void); /* 8001D114.c */
s32 lain_anim_load_site_enter(void); /* 8001D114.c */
void lain_anim_open_slot(s32 index); /* 800220CC.c */
void lain_anim_play_idle(void); /* 8001D114.c */
s32 lain_anim_play_level_move(void); /* 800220CC.c */
s32 lain_anim_play_move(void); /* 800220CC.c */
s32 lain_anim_play_next(void); /* 800220CC.c */
s32 lain_anim_play_save(void); /* 800220CC.c */
s32 lain_anim_play_select(void); /* 800220CC.c */
s32 lain_anim_play_sequence(s32 count); /* 8001D114.c */
s32 lain_anim_play_set6_last(void); /* 8001D114.c */
s32 lain_anim_play_site_enter(void); /* 800220CC.c */
void lain_anim_poll_loads(void); /* 8001D114.c */
s32 lain_anim_ready_level_move(void); /* 800220CC.c */
s32 lain_anim_ready_move(void); /* 800220CC.c */
s32 lain_anim_ready_save(void); /* 800220CC.c */
s32 lain_anim_ready_select(void); /* 800220CC.c */
s32 lain_anim_ready_set6(void); /* 800220CC.c */
s32 lain_anim_ready_site_enter(void); /* 800220CC.c */
void light_apply_preset(void); /* 80023468.c */
s32 light_fade_start(s32 arg0, void *arg1); /* 800281A8.c */
void light_fade_step(void); /* 80023468.c */
void loading_anim_draw(s32 reset); /* 8003D6A8.c */
void loading_anim_load(void); /* 8003D6A8.c */
void loading_anim_reload(void); /* 8003D6A8.c */
void loading_wait_tick(void); /* 80033820.c */
void *lz_decompress(u8 *src, s32 size); /* 800379C8.c */
s32 mcard_accept(void); /* 8003C084.c */
s32 mcard_accept_sync(void); /* 8003C084.c */
void mcard_close_file(void); /* 8003C084.c */
s32 mcard_create_save_file(void); /* 8003C084.c */
s32 mcard_format(void); /* 8003C084.c */
s32 mcard_open_save_file(s32 write); /* 8003C084.c */
s32 mcard_poll(void); /* 8003C084.c */
s32 mcard_read_save(u32 *buf, s32 bytes); /* 8003C084.c */
s32 mcard_start(void); /* 80039734.c */
s32 mcard_unformat(void); /* 8003C084.c */
s32 mcard_write_save(u32 *buf, s32 bytes); /* 8003C084.c */
s32 media_play(s32 movieId, s16 *skipped, s16 *params); /* 80018F48.c */
void media_player_run(void); /* 80018F48.c */
void menu_cell_set_icon(s32 idx); /* 80023468.c */
s32 menu_close(void); /* 80023468.c */
s32 menu_confirm_hide(void); /* 80023468.c */
s32 menu_confirm_show(void); /* 80023468.c */
void menu_draw(void); /* 80023468.c */
void menu_draw_grid_masked(s32 a, s32 b); /* 80023468.c */
void menu_load_texture(void); /* 80023468.c */
s32 menu_open(void); /* 80023468.c */
void menu_render_labels(void); /* 80023468.c */
s32 menu_row_flip_to_icons(s32 row); /* 80023468.c */
s32 menu_row_flip_to_label(s32 row); /* 80023468.c */
s32 menu_run(void); /* 80023468.c */
void menu_sprites_free(void); /* 80023468.c */
void menu_sprites_init(void); /* 80023468.c */
void movie_cd_seek_read(u8 *loc); /* 80018F48.c */
void movie_dct_out_callback(void); /* 80018F48.c */
void movie_decode_frame(void); /* 80018F48.c */
void movie_models_init(void); /* 80031378.c */
void movie_models_update(s16 input); /* 80031378.c */
void movie_start_stream(s32 pos); /* 80018F48.c */
void movie_stop_stream(void); /* 80018F48.c */
void msgbox_draw(s32 menu); /* 80023468.c */
void msgbox_init(void); /* 80023468.c */
s32 name_entry_run(void); /* 80033820.c */
s32 node_cursor_is_media(void); /* 800220CC.c */
s32 node_find_by_keyword(s16 nodeIdx, s16 slot, s16 *outCol, s16 *outRow); /* 800220CC.c */
void node_grid_build(void); /* 800220CC.c */
s32 node_is_displayable(s32 i); /* 800220CC.c */
void node_open_anim_approach(void); /* 8002A344.c */
void node_open_anim_effect(void); /* 8002A344.c */
void node_open_anim_start(void); /* 8002A344.c */
s32 node_pick_select_anim(void); /* 800220CC.c */
void node_reset_all(void); /* 800220CC.c */
void node_unlock_children(s32 nodeIdx, s32 quiet); /* 800220CC.c */
void pad_init(void); /* 80018A38.c */
void pad_read_command(void); /* 80018A38.c */
void pad_read_dpad(void); /* 80018A38.c */
s16 player_get_quit(void); /* 8001D114.c */
void player_load_ui_tim(s32 unused, s16 x, s16 y, s16 clutY); /* 80018F48.c */
void polytan_scene_load(void); /* 8003D6A8.c */
void polytan_scene_run(void); /* 8003D6A8.c */
void ring_models_collapse(void); /* 80031378.c */
void ring_models_init(void); /* 80031378.c */
void ring_models_spin(s32 delay); /* 80031378.c */
s32 save_apply_image(u8 *buf); /* 8003C084.c */
s32 save_build_image(u8 *buf); /* 8003C084.c */
void site_b_load_file(s32 index, void *dest); /* 80018F48.c */
void site_bg_init(void); /* 8002A344.c */
void site_cam_path_start(u32 mode); /* 8002A344.c */
void site_cam_path_step(void); /* 8002A344.c */
s32 site_change_prompt_run(void); /* 8003D1B4.c */
void site_cursor_goto_target(s32 select); /* 80013138.c */
void site_draw_background(void); /* 8002A344.c */
void site_draw_cursor_node(void); /* 8002A344.c */
void site_draw_frame(void); /* 80013138.c */
void site_draw_node_map(void); /* 8002A344.c */
void site_draw_notice(void); /* 8001D114.c */
void site_effects_init(void); /* 8002F4DC.c */
void site_effects_update(void); /* 8002F4DC.c */
void site_end_frame(void); /* 80013138.c */
void site_fade_background(void); /* 8002A344.c */
s32 site_find_nearest_node(s32 mode, s32 dir); /* 80013138.c */
s32 site_get_level_count(void); /* 80018A38.c */
void site_goto_run(void); /* 8002A344.c */
void site_goto_step(void); /* 8002A344.c */
void site_handle_command(void); /* 80013138.c */
void site_init_new_game(void); /* 80018A38.c */
void site_intro_cam_start(void); /* 8002A344.c */
void site_intro_cam_update(void); /* 8002A344.c */
void site_jump_scroll_step(void); /* 8002A344.c */
void site_level_models_place(s32 n, s32 row, s32 angle0, s32 angle1); /* 80029610.c */
void site_load_file(s32 index, void *dest); /* 80018F48.c */
s32 site_move_cursor(s32 dx, s32 dy); /* 80013138.c */
void site_node_model_create(u32 row, u32 col); /* 80029610.c */
void site_node_model_reload(u32 row, u32 col); /* 80029610.c */
void site_orb_fly_start(void); /* 8002F4DC.c */
void site_orb_fly_update(void); /* 8002F4DC.c */
void site_orb_init(void); /* 8002F4DC.c */
void site_orb_update(void); /* 8002F4DC.c */
void site_project_nodes(void); /* 8002A344.c */
void site_reload(void); /* 80018A38.c */
void site_ring_burst_init(void); /* 8002F4DC.c */
void site_ring_burst_update(void); /* 8002F4DC.c */
void site_ring_init(void); /* 8002F4DC.c */
void site_ring_morph_start(void *dst, u32 mode, s32 count); /* 8002F4DC.c */
void site_ring_scroll_texture(void); /* 8002F4DC.c */
void site_ring_update(void); /* 8002F4DC.c */
s32 site_run(void); /* 80013138.c */
void site_scene_init(void); /* 80029610.c */
void site_scene_reset_to_node(u32 index, u32 row); /* 8002A344.c */
void site_scene_update(void); /* 8002A344.c */
void site_set_level_label(s32 number); /* 8002A344.c */
void site_set_node_info(s32 row, s32 col); /* 80013138.c */
void site_streaks_spawn(void); /* 8002F4DC.c */
void sjis_append_number(char *buf, s32 num, s32 pad); /* 8003C084.c */
void slideshow_load_images(void); /* 80018F48.c */
void slideshow_show_image(s16 index); /* 80018F48.c */
void slideshow_update(void); /* 80018F48.c */
void snd_all_keys_off(void); /* 800220CC.c */
void snd_init(s32 quiet); /* 800220CC.c */
void snd_play_anim_sfx(s16 prog); /* 800220CC.c */
void snd_play_sfx(s16 prog); /* 800220CC.c */
void snd_play_sfx_18(void); /* 800220CC.c */
void snd_stop_anim_sfx(void); /* 800220CC.c */
void snd_voice_key_off(s32 voice); /* 800379C8.c */
void snd_voice_key_on_pitched(s32 voice); /* 800379C8.c */
void snd_vsync_update(void); /* 800220CC.c */
void spinner_cell_set_icon(s32 idx); /* 80023468.c */
void spinner_draw(void); /* 80023468.c */
void spinner_free(void); /* 80023468.c */
void spinner_init(const void *unused, s16 arg1); /* 80023468.c */
void spu_cd_audio_off(void); /* 80018F48.c */
void spu_cd_audio_on(void); /* 80018F48.c */
s16 spu_decoded_peak_level(void); /* 8001D114.c */
s16 spu_decoded_peak_level6(void); /* 8001D114.c */
void spu_decoded_xfer_done(void); /* 80018F48.c */
void spu_irq_read_decoded(void); /* 80018F48.c */
s32 sskn_scene_run(void); /* 80039734.c */
void start_menu_run(void); /* 80033820.c */
void text_window_build_message(void); /* 8001D114.c */
void text_window_draw_enter(void); /* 8001D114.c */
void text_window_draw_idle(void); /* 8001D114.c */
void text_window_draw_leave(void); /* 8001D114.c */
void text_window_draw_select(s16 x, s16 y, s32 reset); /* 8001D114.c */
void text_window_init(s16 x, s16 y); /* 8001D114.c */
void text_window_load_cell(s32 row, s32 col); /* 8001D114.c */
void text_window_run(s32 reset); /* 8001D114.c */
void text_window_set_frame_mode(s32 arg0); /* 8001D114.c */
void text_window_set_text(s32 x, s32 y, char *text, s32 mode); /* 8001D114.c */
void text_window_show_cell(s16 arg0, s16 arg1, s32 arg2, s32 arg3); /* 8001D114.c */
void tim_clut_fade_out(u32 *tim); /* 80023468.c */
void tim_clut_fade_toward(u32 *tim, u32 *target); /* 80023468.c */
void tim_load_file(s32 index); /* 80039734.c */
void tim_load_file_at(s32 index, s32 x, s32 y, s32 clut_x, s32 clut_y); /* 80039734.c */
void *tim_load_file_clut(s32 index, s32 clut_x, s32 clut_y); /* 80039734.c */
void tim_upload(u32 *tim); /* 800281A8.c */
void vlc_build_table(u8 *table); /* port_vlc.c */
s32 vlc_decode_frame(u32 *bs, u32 *buf); /* port_vlc.c */
void voice_apply_envelope(s16 *samples); /* 80033820.c */
void voice_concat_clips(u8 *dst); /* 80033820.c */
s32 voice_find_clip(char *name); /* 80033820.c */
s32 voice_load_clip(char *name); /* 80033820.c */
void voice_load_clip_to(char *name, void *dst); /* 80033820.c */
void voice_load_name_table(void); /* 80033820.c */
u8 *voice_synth_romaji(u8 *text, s32 *outSize, u8 *outCount); /* 80033820.c */
void voice_trim_clips(void); /* 80033820.c */
void vram_dump_tim(char *name, s32 mode, s32 x, s32 y, s32 width, s32 height, s32 clutX, s32 clutY); /* 8003CB08.c */
void vsync_counter_tick(void); /* 80013138.c */
void xa_play_channel(s16 channel); /* 80018F48.c */
s32 xa_play_range(s32 pos, s32 arg1); /* 80018F48.c */
void xa_seek_file(void); /* 8001D114.c */
s32 xa_start_read(s32 unused); /* 80018F48.c */
void xa_update(void); /* 80018F48.c */

#endif
