#!/usr/bin/env python3
"""Makes every game function hookable (mod scripts and plugins).

For each function in game/include/game_protos.h, the build compiles a copy of
game/*.c where its definition is renamed lain_orig_<name>, plus a stand-in with
the original name that calls the hook when one is set and the original otherwise.
Calls between game functions therefore go through the hooks too. game/*.c itself
is unchanged.

    python3 tools/gen_hooks.py <out dir>

writes <out dir>/game/*.c (the renamed copies) and <out dir>/game_hooks.c.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROTO = re.compile(r"^(?P<ret>[A-Za-z_][\w \*]*?)\b(?P<name>\w+)\((?P<args>[^;]*)\);\s*/\* (?P<file>[\w.]+) \*/")
SKIP = {"main", "debug_printf"}  # the entry point; a variadic logger


def parse_args(text):
    """[(type, name)] from 'u8 *dest, s32 n'."""
    text = text.strip()
    if text in ("", "void"):
        return []
    out = []
    for i, part in enumerate(p.strip() for p in text.split(",")):
        m = re.match(r"^(.*?)(\w+)$", part)
        ctype = m.group(1).strip() if m and m.group(1).strip() else part
        out.append((ctype, f"a{i}"))
    return out


def load_protos():
    funcs = []
    for line in (ROOT / "game/include/game_protos.h").read_text().splitlines():
        m = PROTO.match(line)
        if not m or m.group("name") in SKIP:
            continue
        funcs.append({"ret": m.group("ret").strip(), "name": m.group("name"),
                      "args": parse_args(m.group("args")), "file": m.group("file")})
    return funcs


def rename_definitions(src, names):
    """Renames the definitions (a function name at the start of a declarator
    followed by '(' and later '{') of the listed functions, nothing else."""
    pattern = re.compile(r"^(?!static\b|extern\b|typedef\b|#)([A-Za-z_][\w \*]*?\b)(" +
                         "|".join(sorted(names, key=len, reverse=True)) + r")(\s*\([^;{)]*\)\s*\{)", re.M)
    return pattern.sub(lambda m: m.group(1) + "lain_orig_" + m.group(2) + m.group(3), src)


def is_pointer(ctype):
    return "*" in ctype


def main():
    out = Path(sys.argv[1])
    (out / "game").mkdir(parents=True, exist_ok=True)
    funcs = load_protos()
    by_file = {}
    for f in funcs:
        by_file.setdefault(f["file"], set()).add(f["name"])
    renamed = 0
    for src in sorted((ROOT / "game").glob("*.c")):
        text = src.read_text()
        if src.name in by_file:
            new = rename_definitions(text, by_file[src.name])
            renamed += len(re.findall(r"\blain_orig_\w+\s*\(", new)) - len(re.findall(r"\blain_orig_\w+\s*\(", text))
            text = new
            # A plain declaration of each renamed function, so one defined `inline`
            # still gets an external definition (C99 6.7.4).
            decls = [f"{f['ret']} lain_orig_{f['name']}({', '.join(f'{t} {n}' for t, n in f['args']) or 'void'});"
                     for f in funcs if f["file"] == src.name]
            text += "\n" + "\n".join(decls) + "\n"
        # the copy compiles from the build folder: point error messages at the real file
        dest = out / "game" / src.name
        body = f'#line 1 "{src.as_posix()}"\n' + text
        if not dest.exists() or dest.read_text() != body:
            dest.write_text(body)
    if renamed != len(funcs):
        sys.exit(f"gen_hooks: renamed {renamed} definitions, expected {len(funcs)}")

    c = ['/* Generated by port/tools/gen_hooks.py. Do not edit. */',
         '#include "common.h"',
         '#include "game_hooks.h"',
         '']
    for i, f in enumerate(funcs):
        params = ", ".join(f"{t} {n}" for t, n in f["args"]) or "void"
        names = ", ".join(n for _, n in f["args"])
        ret, name = f["ret"], f["name"]
        c.append(f"{ret} lain_orig_{name}({params});")
        c.append(f"static {ret} (*hook_{name})({params});")
        # the stand-in the game calls
        call = f"(hook_{name} ? hook_{name} : lain_orig_{name})({names})"
        c.append(f"{ret} {name}({params}) {{ {'' if ret == 'void' else 'return '}{call}; }}")
        # generic call of a function with this signature (the original, a
        # plugin's replacement, ...): arguments and result as 64-bit integers
        conv = ", ".join(f"({t})(intptr_t)a[{k}]" if is_pointer(t) else f"({t})a[{k}]"
                         for k, (t, _) in enumerate(f["args"]))
        fn = f"(({ret} (*)({params}))fn)"
        if ret == "void":
            body = f"{fn}({conv}); return 0;"
        elif is_pointer(ret):
            body = f"return (int64_t)(intptr_t){fn}({conv});"
        else:
            body = f"return (int64_t){fn}({conv});"
        c.append(f"static int64_t call_{name}(void *fn, const int64_t *a) {{ (void)a; {body} }}")
        # the adapter a generic hook installs: arguments to integers, result back
        pack = ", ".join(f"(int64_t)(intptr_t){n}" if is_pointer(t) else f"(int64_t){n}" for t, n in f["args"])
        arr = f"int64_t a[] = {{{pack}}};" if f["args"] else "const int64_t *a = 0;"
        disp = f"lain_game_dispatch_fn({i}, a, {len(f['args'])})"
        if ret == "void":
            back = f"{disp};"
        elif is_pointer(ret):
            back = f"return ({ret})(intptr_t){disp};"
        else:
            back = f"return ({ret}){disp};"
        c.append(f"static {ret} adapt_{name}({params}) {{ {arr} {back} }}")
        c.append("")
    c.append("int64_t (*lain_game_dispatch_fn)(int index, const int64_t *args, int nargs);")
    c.append("")
    c.append("const LainGameFn lain_game_fns[] = {")
    for f in funcs:
        sig = f"{f['ret']} ({', '.join(t for t, _ in f['args']) or 'void'})"
        # argument kinds, result first: v void, p pointer, i signed, u unsigned
        kind = lambda t: "v" if t == "void" else "p" if is_pointer(t) else "u" if t.startswith("u") or "unsigned" in t else "i"
        kinds = kind(f["ret"]) + "".join(kind(t) for t, _ in f["args"])
        c.append(f'    {{"{f["name"]}", "{sig}", "{kinds}", {len(f["args"])}, (void **)&hook_{f["name"]}, '
                 f'(void *){f["name"]}, (void *)lain_orig_{f["name"]}, (void *)adapt_{f["name"]}, call_{f["name"]}}},')
    c.append("};")
    c.append(f"const int lain_game_fn_count = {len(funcs)};")

    # Game variables by name: PS1 address and size (game/generated/symbols.txt);
    # the host-typed globals (game/PORT_TYPES.md) live outside the arena.
    table = (ROOT / "game/PORT_TYPES.md").read_text().split("## Host-typed globals", 1)[1].split("\n## ", 1)[0]
    host = set(re.findall(r"^\|\s*([A-Za-z_]\w*)\s*\|[^|]*\|[^|]*\[\w+\.c\]", table, re.M))
    syms = []
    for line in (ROOT / "game/generated/symbols.txt").read_text().splitlines():
        if line.startswith("#"):
            continue
        name, addr, size = line.split()
        syms.append((name, int(addr, 16), int(size, 16)))
    for name in sorted(host):
        c.append(f"extern char {name}[];")
    c.append("const LainSymbol lain_symbols[] = {")
    for name, addr, size in syms:
        c.append(f'    {{"{name}", 0x{addr:08X}u, 0x{size:X}u, {name if name in host else "0"}}},')
    c.append("};")
    c.append(f"const int lain_symbol_count = {len(syms)};")
    (out / "game_hooks.c").write_text("\n".join(c) + "\n")
    print(f"gen_hooks: {len(funcs)} hookable game functions")


if __name__ == "__main__":
    main()
