#!/usr/bin/env python3
"""Generate game/generated/symbols.txt: every named game variable with its PS1
address and size (from ../config/symbol_addrs.txt), for the mod system's names
(tools/gen_hooks.py). The port builds from port/ alone, so the list lives here.

    python3 tools/gen_symbols.py
"""
import re
from pathlib import Path

PORT = Path(__file__).resolve().parent.parent
out = ["# Generated by port/tools/gen_symbols.py. Do not edit. name address size"]
for line in (PORT.parent / "config/symbol_addrs.txt").read_text().splitlines():
    m = re.match(r"^(\w+)\s*=\s*0x([0-9A-Fa-f]+);(.*)$", line)
    if not m or "type:func" in m.group(3):
        continue
    addr = int(m.group(2), 16)
    size = re.search(r"size:0x([0-9A-Fa-f]+)", m.group(3))
    if 0x80000000 <= addr < 0x80200000:
        out.append(f"{m.group(1)} 0x{addr:08X} 0x{int(size.group(1), 16) if size else 0:X}")
(PORT / "game/generated/symbols.txt").write_text("\n".join(out) + "\n")
print(f"{len(out) - 1} game variables")
