#!/usr/bin/env python3
"""Generate game/include/game_protos.h: a prototype for every game function,
taken from its definition in game/*.c, so every file sees one signature.

    python3 tools/gen_protos.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEF = re.compile(r"^(?!static\b|extern\b|typedef\b|#)([A-Za-z_][\w \*]*?\b(\w+)\s*\(([^;{)]*)\))\s*\{",
                 re.M)
# Game functions: splat placeholders and the names in config/symbol_addrs.txt.
NAMED = set(re.findall(r"^(\w+)\s*=\s*0x[0-9A-Fa-f]+;.*type:func", (ROOT.parent / "config/symbol_addrs.txt").read_text(), re.M))


def is_game_function(name: str) -> bool:
    return name == "main" or name in NAMED or re.fullmatch(r"func_[0-9A-F]{8}", name) is not None


protos = {}
for c in sorted((ROOT / "game").glob("*.c")):
    text = c.read_text()
    for m in DEF.finditer(text):
        sig = " ".join(m.group(1).split())
        name = m.group(2)
        if name == "main" or not is_game_function(name):
            continue
        sig = re.sub(r"^inline\s+", "", sig)
        protos.setdefault(name, (sig, c.name))
BASIC = {"void", "char", "int", "short", "long", "unsigned", "signed", "const", "volatile",
         "s8", "u8", "s16", "u16", "s32", "u32"}


def basic_only(sig: str) -> bool:
    """Only prototypes whose types are all basic can live in a shared header;
    ones using per-file struct typedefs stay as the files' own declarations."""
    words = set(re.findall(r"[A-Za-z_]\w*", sig)) - {sig.split("(")[0].split()[-1].strip("*")}
    params = re.findall(r"[A-Za-z_]\w*", sig.split("(", 1)[1])
    ret = re.findall(r"[A-Za-z_]\w*", sig.split("(", 1)[0])[:-1]
    names = set()
    for part in sig.split("(", 1)[1].rstrip(")").split(","):
        toks = re.findall(r"[A-Za-z_]\w*", part)
        if len(toks) > 1:
            names.add(toks[-1])  # parameter name
    return all(t in BASIC for t in (set(params) | set(ret)) - names)


protos = {k: v for k, v in protos.items() if basic_only(v[0])}
out = ["/* Generated by port/tools/gen_protos.py from the game .c definitions. Do not edit. */",
       "#ifndef GAME_PROTOS_H", "#define GAME_PROTOS_H", ""]
for name in sorted(protos):
    sig, where = protos[name]
    out.append(f"{sig}; /* {where} */")
out += ["", "#endif", ""]
(ROOT / "game/include/game_protos.h").write_text("\n".join(out))
print(f"{len(protos)} prototypes")
