#!/usr/bin/env python3
"""Generate game/generated/psx_arena.S: the PS1 RAM arena plus one label per game
global at its original address. Addresses come from the splat output (symbol
names and addresses only; no game data is written).

Symbols whose host representation differs from the PS1 layout (pointer-typed
globals and structs with pointer members, listed in game/PORT_TYPES.md) are
left out: they are real host globals, relocated by the data loader.

    python3 tools/gen_arena.py      (needs ../asm and ../config from `make split`)
"""
import re
from pathlib import Path

PORT = Path(__file__).resolve().parent.parent
ROOT = PORT.parent
BASE, SIZE = 0x80000000, 0x200000
# Host-only space after PS1 RAM: the game heap (see game/include/psx_arena.h).
HEAP_EXT = 0x200000

addrs: dict[str, int] = {}
for s in (ROOT / "asm").rglob("*.s"):
    for m in re.finditer(r"^\s*dlabel ((?:D|jtbl)_([0-9A-F]{8}))", s.read_text(), re.M):
        addrs[m.group(1)] = int(m.group(2), 16)
p = ROOT / "config/undefined_syms_auto.txt"
if p.exists():
    for m in re.finditer(r"^(D_[0-9A-F]{8})\s*=\s*0x([0-9A-Fa-f]+)", p.read_text(), re.M):
        addrs[m.group(1)] = int(m.group(2), 16)
# Named globals (every non-function entry of symbol_addrs.txt).
for m in re.finditer(r"^(\w+)\s*=\s*0x([0-9A-Fa-f]+);(.*)$", (ROOT / "config/symbol_addrs.txt").read_text(), re.M):
    if "type:func" not in m.group(3):
        addrs[m.group(1)] = int(m.group(2), 16)

src = "\n".join(c.read_text() for c in (PORT / "game").glob("*.c"))
used = sorted((n for n in addrs if re.search(rf"\b{n}\b", src)), key=lambda n: (addrs[n], n))

excluded = set()
pt = PORT / "game/PORT_TYPES.md"
if pt.exists():
    # Rows in the "Host-typed globals" table: | symbol | ...
    section = pt.read_text().split("## Host-typed globals", 1)
    if len(section) == 2:
        excluded = set(re.findall(r"^\|\s*([A-Za-z_]\w*)\s*\|", section[1].split("\n## ", 1)[0], re.M)) - {"Symbol"}

lines = [
    "/* Generated by port/tools/gen_arena.py. Do not edit. Names/addresses only. */",
    "#ifdef __APPLE__",
    "#define SYM(x) _##x",
    "#else",
    "#define SYM(x) x",
    "#endif",
    "    .data",
    "    .p2align 4",
    "    .globl SYM(psx_arena)",
    "SYM(psx_arena):",
    f"    .space 0x{SIZE + HEAP_EXT:X}",
    "",
]
count = 0
for n in used:
    a = addrs[n]
    if n in excluded or not (BASE <= a < BASE + SIZE):
        continue
    lines.append(f"    .globl SYM({n})")
    lines.append(f"    .set SYM({n}), SYM(psx_arena) + 0x{a - BASE:X}")
    count += 1
(PORT / "game/generated/psx_arena.S").write_text("\n".join(lines) + "\n")
print(f"{count} globals in the arena, {len(excluded)} host-typed, {len(used)} referenced")
